spring.application.name=MarginHotelManagement

spring.datasource.url = jdbc:mysql://localhost:3306/marginhoteldb?createDatabaseIfNotExist=true
spring.datasource.username = root
spring.datasource.password = password
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

server.servlet.context-path = /marginhotel

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

server.port = 8080

jwt.secret=KRb1Ddy18uF6w1y17srwEVAAp8E2L5kis2tN1BRp6dw=
jwt.expiration-ms=86400000

app.admin.email=admin@marginhotel.com
app.admin.password=adminpassword123